using System;
using System.Collections.Generic;

namespace ProjectEuler
{
    /// <summary>
    ///     Even Fibonacci numbers
    ///     Problem 2
    ///        
    ///     Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    ///
    ///     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    ///
    ///     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class _002
    {
        public _002()
        {
            List<int> fibonacci = new List<int> { 0, 1 };

            const int fourMillion = 4000000;
            int num = 0;
            int sum = 0;
            int i = 2;

            while (num < fourMillion)
            {
                num = fibonacci[i-1] + fibonacci[i-2];
                fibonacci.Add(num);

                if (num % 2 == 0) { sum += num; }

                i++;
            }

            Console.WriteLine("{0}", sum);
        }
    }
}





